swagger: "2.0"
info:
  version: "1.0.0"
  title: e-CareSmart API
  x-logo:
    url: /images/ecaresmart-sm.png
  contact:
    email: info@cassidye-care.com
  description: |
    # Overview
    The e-CareSmart API is a RESTful API that provides data exchange between the e-CareSmart platform's mobile and web applications.
    
    The e-CareSmart API supports JSON formatted requests and responses for sending and receicing data. Data communication is done over a secured SSL channel.
    
    # Authentication
    
    
# during dev, should point to your local machine
host: localhost:10020
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
